# config-management.yaml

apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  # clusterName is required and must be unique among all managed clusters
  clusterName: example-cluster
  git:
    syncRepo: git@github.com:tushgup/gcloud-test.git
    syncBranch: 1.0.0
    secretType: ssh
    policyDir: 
